name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_ACCOUNT_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_ACCOUNT_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_ACCOUNT_EMAIL}}
          usedocker: true
          docker_heroku_process_type: worker
          stack: container
        env: 
          HD_TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          HD_TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          HD_TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          HD_REDIS_HOST: ${{ secrets.REDIS_HOST }}